module.exports = {
  apps: [
    {
      name: "niome-seed-bridge-dollar4",
      cwd: "/home/administrator/workspace/subnet-niome",
      script: "tools/live_seed_bridge.py",
      interpreter: "/home/administrator/workspace/subnet-niome/.venv/bin/python",
      autorestart: true,
      watch: false,
      max_memory_restart: "1200M",
      kill_timeout: 10000,
      env: {
        NIOME_ARTIFACT_ROOT: "/home/administrator/workspace/subnet-niome/artifacts/miners/dollar4",
        NIOME_EXPLORATION_PROFILE: "5HKLhT3ie4VkW9hG3Vgn2MiYgZ9PQtVnFbJ18fmDh5ZkWY86",
      },
    },
    {
      name: "niome-dollar4",
      cwd: "/home/administrator/workspace/subnet-niome",
      script: "/home/administrator/workspace/subnet-niome/.venv/bin/python",
      interpreter: "none",
      args: "neurons/miner.py --netuid 55 --network finney --wallet main4 --wallet-hotkey hype2 --wallet-path /home/administrator/.bittensor/wallets/main --axon.port 8094 --axon.external-ip 69.30.204.53 --blacklist.force_validator_permit",
      autorestart: true,
      watch: false,
      max_memory_restart: "1200M",
      kill_timeout: 15000,
      env: {
        PYTHONPATH: "/home/administrator/workspace/subnet-niome",
        NIOME_ARTIFACT_ROOT: "/home/administrator/workspace/subnet-niome/artifacts/miners/dollar4",
      },
    },
    {
      name: "niome-dashboard-dollar4",
      cwd: "/home/administrator/workspace/subnet-niome",
      script: "tools/niome_dashboard.py",
      interpreter: "/home/administrator/workspace/subnet-niome/.venv/bin/python",
      autorestart: true,
      watch: false,
      max_memory_restart: "450M",
      kill_timeout: 10000,
      env: {
        NIOME_DASH_HOST: "0.0.0.0",
        NIOME_DASH_PORT: "8114",
        NIOME_DASH_NETWORK: "finney",
        NIOME_DASH_ARTIFACT_ROOT: "/home/administrator/workspace/subnet-niome/artifacts/miners/dollar4",
        NIOME_DASH_MINER_HOTKEY: "5HKLhT3ie4VkW9hG3Vgn2MiYgZ9PQtVnFbJ18fmDh5ZkWY86",
        NIOME_DASH_MINER_PROCESS: "niome-dollar4",
        NIOME_DASH_BRIDGE_PROCESS: "niome-seed-bridge-dollar4",
        NIOME_DASH_GUIDE_VARIANTS: "72",
        NIOME_DASH_PRIMARY_CAS_SHARE: "0.60",
      },
    },
  ],
};
